spring:
  profiles:
    active:
      - test
#      - ${EXPEDIA_ENVIRONMENT:test}  //with use SYSTEM VARIABLES or SPRING_PROFILES_ACTIVE
  application:
    name: "music_player_Rest_Client"
---

spring:
  config:
    activate:
      on-profile: test

#  datasource:                                    //this is redundant
#    driver-class-name: "org.hsqldb.jdbcDriver"
#    url: "jdbc:hsqldb:mem:testbase"
#    username: "sa"
#    password:

name: test-YAML
environment: testing

port: 0
host: "http://localhost:"

---

spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production


---


spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client
    username: root
    password: root

name: ${DEV_NAME:dev-YAML}
environment: development

server:
  port: 8081

port: 8080
host: "http://localhost:"

