spring:
  profiles:
    active:
      - test
#      - ${EXPEDIA_ENVIRONMENT:test}  //with use SYSTEM VARIABLES or SPRING_PROFILES_ACTIVE
  application:
    name: "music_player_Rest_Client"
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: "org.hsqldb.jdbcDriver"
    url: "jdbc:hsqldb:mem:testbase"
    username: "sa"
    password:

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

name: test-YAML
environment: testing

port: 0
host: "http://localhost:"

---

spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production


---


spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: "org.hsqldb.jdbc.JDBCDriver"
    url: "jdbc:hsqldb:hsql://localhost/"
    username: "sa"
    password:
  jpa:
    hibernate:
      ddl-auto: update

name: ${DEV_NAME:dev-YAML}
environment: development

server:
  port: 8081

port: 8080
host: "http://localhost:"

